In [3]:
import numpy as np
import pandas as pd
df = pd.read_csv(r'D:\Projects\FIFA WORLD CUP Project\dataset\results.csv')
df.head()

         date home_team away_team  home_score  away_score tournament     city   country  neutral
0  1872-11-30  Scotland   England         0.0         0.0   Friendly  Glasgow  Scotland    False
1  1873-03-08   England  Scotland         4.0         2.0   Friendly   London   England    False
2  1874-03-07  Scotland   England         2.0         1.0   Friendly  Glasgow  Scotland    False
3  1875-03-06   England  Scotland         2.0         2.0   Friendly   London   England    False
4  1876-03-04  Scotland   England         3.0         0.0   Friendly  Glasgow  Scotland    False

In [4]:
print(f"\nTotal rows and columns: {df.shape}")

Total rows and columns: (49287, 9)

In [5]:
df.tail

<bound method NDFrame.tail of              date home_team   away_team  home_score  ...      tournament             city        country neutral
0      1872-11-30  Scotland     England         0.0  ...        Friendly          Glasgow       Scotland   False
1      1873-03-08   England    Scotland         4.0  ...        Friendly           London        England   False
2      1874-03-07  Scotland     England         2.0  ...        Friendly          Glasgow       Scotland   False
3      1875-03-06   England    Scotland         2.0  ...        Friendly           London        England   False
4      1876-03-04  Scotland     England         3.0  ...        Friendly          Glasgow       Scotland   False
...           ...       ...         ...         ...  ...             ...              ...            ...     ...
49282  2026-06-27    Jordan   Argentina         NaN  ...  FIFA World Cup        Arlington  United States    True
49283  2026-06-27  Colombia    Portugal         NaN  ...  FIFA World Cup    Miami Gardens  United States    True
49284  2026-06-27  DR Congo  Uzbekistan         NaN  ...  FIFA World Cup          Atlanta  United States    True
49285  2026-06-27    Panama     England         NaN  ...  FIFA World Cup  East Rutherford  United States    True
49286  2026-06-27   Croatia       Ghana         NaN  ...  FIFA World Cup     Philadelphia  United States    True

[49287 rows x 9 columns]>

In [9]:
df['date'] = pd.to_datetime(df['date'])
df = df[df['date'] <= '2026-05-09']
df.tail()

C:\Users\SUBHAJOTI PATRA\AppData\Local\Temp\ipykernel_9816\1141603363.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['date'] = pd.to_datetime(df['date'])

            date               home_team away_team  ...       city                 country neutral
49208 2026-03-31  Bosnia and Herzegovina     Italy  ...     Zenica  Bosnia and Herzegovina   False
49209 2026-03-31                  Sweden    Poland  ...      Solna                  Sweden   False
49210 2026-03-31                  Kosovo    Turkey  ...   Pristina                  Kosovo   False
49211 2026-03-31          Czech Republic   Denmark  ...     Prague          Czech Republic   False
49213 2026-03-31               Australia   Curaçao  ...  Melbourne               Australia   False

[5 rows x 9 columns]

In [10]:
qualified_teams = [
    'Canada', 'Mexico', 'United States', 'Japan', 'New Zealand', 
    'Iran', 'Argentina', 'Uzbekistan', 'Jordan', 'South Korea', 
    'Australia', 'Brazil', 'Ecuador', 'Paraguay', 'Uruguay', 
    'Colombia', 'Morocco', 'Tunisia', 'Egypt', 'Algeria', 
    'Ghana', 'Cape Verde', 'Qatar', 'Saudi Arabia', 'Senegal', 
    'South Africa', 'Ivory Coast', 'England', 'France', 'Croatia', 
    'Portugal', 'Norway', 'Germany', 'Netherlands', 'Switzerland', 
    'Scotland', 'Spain', 'Austria', 'Belgium', 'Panama', 
    'Curaçao', 'Haiti', 'Bosnia and Herzegovina', 'Sweden', 'Turkey', 
    'Czech Republic', 'DR Congo', 'Iraq'
]
df = df[df['home_team'].isin(qualified_teams) | df['away_team'].isin(qualified_teams)]
df.shape

(25842, 9)

In [11]:
df.tail()

            date               home_team away_team  ...       city                 country neutral
49208 2026-03-31  Bosnia and Herzegovina     Italy  ...     Zenica  Bosnia and Herzegovina   False
49209 2026-03-31                  Sweden    Poland  ...      Solna                  Sweden   False
49210 2026-03-31                  Kosovo    Turkey  ...   Pristina                  Kosovo   False
49211 2026-03-31          Czech Republic   Denmark  ...     Prague          Czech Republic   False
49213 2026-03-31               Australia   Curaçao  ...  Melbourne               Australia   False

[5 rows x 9 columns]

In [16]:
df = df[df['tournament'] != 'Friendly']
df.shape

(15371, 9)

In [17]:
df = df.sort_values('date', ascending=False)
recent_matches_list = []
for team in qualified_teams:
    team_matches = df[(df['home_team'] == team) | (df['away_team'] == team)].head(20)
    recent_matches_list.append(team_matches)
df_last_20 = pd.concat(recent_matches_list)
df_last_20 = df_last_20.drop_duplicates()
df_last_20 = df_last_20.sort_values('date', ascending=False)
print(f"New DataFrame size: {df_last_20.shape}")
df_last_20.head()

New DataFrame size: (812, 9)

            date               home_team away_team  ...      city                 country neutral
49206 2026-03-31                DR Congo   Jamaica  ...   Zapopan                  Mexico    True
49208 2026-03-31  Bosnia and Herzegovina     Italy  ...    Zenica  Bosnia and Herzegovina   False
49210 2026-03-31                  Kosovo    Turkey  ...  Pristina                  Kosovo   False
49211 2026-03-31          Czech Republic   Denmark  ...    Prague          Czech Republic   False
49209 2026-03-31                  Sweden    Poland  ...     Solna                  Sweden   False

[5 rows x 9 columns]

In [21]:
df = df_last_20
conditions = [df['home_score'] > df['away_score'],df['away_score'] > df['home_score']]
choices = [df['home_team'],df['away_team']]
df['Winner'] = np.select(conditions,choices,default='Draw')
df = df.reset_index(drop=True)
df.insert(0,'Serial_No',range(1,len(df)+1))
df.head()

   Serial_No       date               home_team away_team  ...      city                 country neutral    Winner
0          1 2026-03-31                DR Congo   Jamaica  ...   Zapopan                  Mexico    True  DR Congo
1          2 2026-03-31  Bosnia and Herzegovina     Italy  ...    Zenica  Bosnia and Herzegovina   False      Draw
2          3 2026-03-31                  Kosovo    Turkey  ...  Pristina                  Kosovo   False    Turkey
3          4 2026-03-31          Czech Republic   Denmark  ...    Prague          Czech Republic   False      Draw
4          5 2026-03-31                  Sweden    Poland  ...     Solna                  Sweden   False    Sweden

[5 rows x 11 columns]

In [25]:
df['home_score'] = df['home_score'].fillna(0)
df['away_score'] = df['away_score'].fillna(0)
df['home_score'] = df['home_score'].astype(int)
df['away_score'] = df['away_score'].astype(int)
df['city'] = df['city'].str.title()
df['country'].str.title()
df.isnull().sum()

Serial_No     0
date          0
home_team     0
away_team     0
home_score    0
away_score    0
tournament    0
city          0
country       0
neutral       0
Winner        0
dtype: int64

In [26]:
df.head()

   Serial_No       date               home_team away_team  ...      city                 country neutral    Winner
0          1 2026-03-31                DR Congo   Jamaica  ...   Zapopan                  Mexico    True  DR Congo
1          2 2026-03-31  Bosnia and Herzegovina     Italy  ...    Zenica  Bosnia and Herzegovina   False      Draw
2          3 2026-03-31                  Kosovo    Turkey  ...  Pristina                  Kosovo   False    Turkey
3          4 2026-03-31          Czech Republic   Denmark  ...    Prague          Czech Republic   False      Draw
4          5 2026-03-31                  Sweden    Poland  ...     Solna                  Sweden   False    Sweden

[5 rows x 11 columns]

In [30]:
!pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in c:\users\subhajoti patra\anaconda3\lib\site-packages (2.9.12)

In [31]:
from sqlalchemy import create_engine
db_url = "postgresql://postgres.file@aws-1-ap-3/postgres"
try:
    engine = create_engine(db_url)
    df.to_sql('world_cup_stats',engine,if_exists='replace',index=False)
    print("done")
except Exception as e:
    print(f"connection failed: {e}")

done